### ISSUE TITLE
Install Error 127 make config step

### ISSUE THREAD

**Issue by throro** [aol/moloch#1062] opened 2019-05-19 01:59 UTC
Moloch version: idk i just clone with git

OS name and version: ubuntu server 19.04

How was Moloch built/installed: (rpm, deb, easybutton, ...): easybutton

Logs:
make[1]: Leaving directory '/moloch/tests'
cc --shared -o ../lua.so -g -O2 -Wall -Wextra -D_GNU_SOURCE -fPIC -I../.. -I../../thirdparty -I/moloch/thirdparty/glib-2.56.2/glib -I/moloch/thirdparty/glib-2.56.2 -I/moloch/thirdparty/glib-2.56.2/gmodule -I/moloch/thirdparty/glib-2.56.2/gobject -I/moloch/thirdparty/lua-5.3.5/src session.c molua.c httpService.c data.c /moloch/thirdparty/lua-5.3.5/src/liblua.a
MOLOCH: Installing node 8.15.0
--2019-05-19 01:35:52-- https://nodejs.org/download/release/v8.15.0/node-v8.15.0-linux-x64.tar.xz
Resolving nodejs.org (nodejs.org)... 104.20.22.46, 104.20.23.46, 2606:4700:10::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11322992 (11M) [application/x-xz]
Saving to: ‘node-v8.15.0-linux-x64.tar.xz’

node-v8.15.0-linux-x 100%[===================>] 10.80M 3.76MB/s in 2.9s

2019-05-19 01:35:55 (3.76 MB/s) - ‘node-v8.15.0-linux-x64.tar.xz’ saved [11322992/11322992]

MOLOCH: Now type 'sudo make install' and 'sudo make config'
root@lab0:/moloch# ^C
root@lab0:/moloch# sudo make install
Making install in .
make[1]: Entering directory '/moloch'
make[2]: Entering directory '/moloch'
npm ci
/bin/bash: npm: command not found
make[2]: *** [Makefile:752: install-exec-local] Error 127
make[2]: Leaving directory '/moloch'
make[1]: *** [Makefile:644: install-am] Error 2
make[1]: Leaving directory '/moloch'
make: *** [Makefile:329: install-recursive] Error 1
root@lab0:/moloch# sudo make condig
make: *** No rule to make target 'condig'. Stop.
root@lab0:/moloch# sudo make config
/data/moloch/bin/Configure
/bin/bash: /data/moloch/bin/Configure: No such file or directory
make: *** [Makefile:763: config] Error 127

**Comment by throro** [comment] 2019-05-19 02:32
i just install npm, and now have this error

> fs-ext@0.5.0 install /moloch/viewer/node_modules/fs-ext
> node-gyp configure build

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/moloch/viewer/node_modul                                                                                       es/fs-ext/build'
gyp ERR! System Linux 5.0.0-15-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /moloch/viewer/node_modules/fs-ext
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@0.5.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-ext@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logg                                                                                       ing output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-19T02_30_52_817Z-debug.log
make[1]: *** [Makefile:18: install] Error 1
make[1]: Leaving directory '/moloch/viewer'
make: *** [Makefile:329: install-recursive] Error 1
root@lab0:/moloch#

**Comment by awick** [comment] 2019-05-20 22:32
duplicate of #1057

**Closed by awick** 2019-05-20 22:32 UTC
