### ISSUE TITLE
It is empty about suricata in webUI

### ISSUE THREAD

**Issue by zhy0830** [aol/moloch#1167] opened 2019-09-17 11:52 UTC
I have a question.suricata do not have packet

more config.ini | grep suricata
plugins=suricata.so
suricataAlertFile=/var/log/suricata/eve.json
suricataExpireMinutes=6000

Elasticsearch version:
elasticsearch:6.7.1

Moloch version:
moloch-capture 2.0.0-GIT/v1.8.0-59-g5911bcbf session size=392 packet size=80 api=160

Suricata version:
This is Suricata version 3.1 RELEASE

OS name and version:
centOS7

How was Moloch built/installed: (rpm, deb, easybutton, ...)
easybutton

there are alert in eve.json

**Comment by awick** [comment] 2019-09-17 12:47
duplicate of #1058

**Closed by awick** 2019-09-17 12:47 UTC
