### ISSUE TITLE
Sorting on http.uri return error "No results or none that match your search within your time range."

### ISSUE THREAD

**Issue by jakup** [aol/moloch#801] opened 2018-02-16 01:31 UTC
**Elasticsearch version**: 5.6
**Moloch version**: v0.50.0

Can reproduce on https://demo.molo.ch

**steps to reproduce**:
- Toggle Http/URI Column Visibility.
- Click URI Column to sort.
- Observe No results error

**Comment by awick** [comment] 2018-02-16 11:55
This is caused by changes in ES 5 and how we created mappings.  It is fixed in 1.0

**Closed by awick** 2018-02-16 11:55 UTC
