### ISSUE TITLE
Query does not carry over from SPI View to Sessions tab switch

### ISSUE THREAD

**Issue by amaddalena** [aol/moloch#649] opened 2017-03-03 18:19 UTC
After editing your query while on the SPI View if you click the Sessions tab the edited query on the SPI Tab does not persist to the Sessions tab and loses the newest variable added (eg click and ad a http.hostname as an AND clause)

v0.18.0-GIT Moloch

**Comment by WilliamSalusky** [comment] 2017-03-03 21:29
This is because the update of the query has not been applied to the local DOM. If you were to run the query, it would then transfer between tab/pages.

**Comment by amaddalena** [comment] 2017-03-03 21:55
Interesting. I have tried it after running on the spi view (if http.host
was added I run the query in SPI so only relevant http.host==%s data is
shown in spi then hop to sessions) to no avail.

**Comment by 31453** [comment] 2017-03-20 15:09
@amaddalena Is this an issue even when the query has been applied to the view? If so, can you list the exact steps to reproduce?

**Comment by awick** [comment] 2017-03-26 14:08
This was a useful feature from previous version
1) start with empty query
2) go to spiview 
3)  type "ip = 1.2.3.4", do NOT hit enter or search
4) click sessions
5) query is empty

Repeat with spiview.old and you'll see the search box has the same value after clicking

**Comment by awick** [comment] 2017-04-06 00:37
So I should have written a 
6) hit the back button
7) query should be "ip = 1.2.3.4" still but NOT executed.

**Comment by 31453** [comment] 2017-05-11 17:05
fixed in 7de3fa2

**Closed by 31453** 2017-05-11 17:05 UTC
Labels: 1 point
