### ISSUE TITLE
pcap read error "invalid file capture length 4294967295, bigger than maximum of 262144"

### ISSUE THREAD

**Issue by jescar50dx** [aol/moloch#586] opened 2017-01-18 19:13 UTC
**Elasticsearch version**: 2.4

**Moloch version**: moloch-nightly.x86_64 0:0.17.1_GIT-125

**OS name and version**: CentOS 6.8

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) RPM

**Provide logs, stack traces and steps to reproduce**:

Didn't have this issue with an earlier build. Reverted back to build moloch-nightly.x86_64 0:0.17.0_GIT-90 for now.

Jan 18 18:23:54 reader-libpcap-file.c:278 reader_libpcapfile_next(): Couldn't process 'foo.pcap' error 'invalid file capture length 4294967295, bigger than maximum of 262144'

**Comment by awick** [comment] 2017-01-21 22:18
Can you provide a sample pcap file?  You can send on slack or email to andywick @ gmail

**Comment by awick** [comment] 2017-01-22 19:09
This is caused by moloch using newer version of libpcap and suricata sets a value that libpcap doesn't like. This has been fixed in newer versions of suricata. 

If you can't update but you can recompile suricata then edit src/log-pcap.c and change the call to `pcap_open_dead` so the second argument is `262144` instead of `-1`

**Closed by awick** 2017-01-22 19:09 UTC

**Comment by misi1987107** [comment] 2019-08-06 02:30
Hello，I have the same problem. How do you solve it?

**Comment by misi1987107** [comment] 2019-08-07 03:22
> **Elasticsearch版本**：2.4
> 
> **Moloch版本**：moloch-nightly.x86_64 0：0.17.1_GIT-125
> 
> **操作系统名称和版本**：CentOS 6.8
> 
> **Moloch是如何构建/安装的：**（rpm，deb，singlehost built，...）RPM
> 
> **提供日志，堆栈跟踪和重现步骤**：
> 
> 早期版本没有此问题。现在恢复建立moloch-nightly.x86_64 0：0.17.0_GIT-90。
> 
> 1月18日18:23:54 reader-libpcap-file.c：278 reader_libpcapfile_next（）：无法处理'foo.pcap'错误'无效文件捕获长度4294967295，大于最大值262144'

hell ，do you resolve it?how to do.

**Comment by awick** [comment] 2019-08-07 10:33
Moloch 0.17 is no longer supported, please upgrade
