### ISSUE TITLE
WISE - "Right-Click" works for some users but not all.

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#753] opened 2017-10-25 16:01 UTC
**Elasticsearch version**:
2.4.4
**Moloch version**:
19.2
**OS name and version**:
Windows 7 
**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
modified moloch/etc/config.ini by adding values: 
```
plugins=wise.so; tagger.so
viewerPlugins=wise.js
```
Modified moloch/wiseService/wiseService.ini by added the following:
```
[right-click:Virus-Total]
file=virustotal-rightclick.ini

[right-click:Anomaly]
file=anomaly-rightclick.ini

[right-click:AlienVault]
file=alienvault-rightclick.ini

[right-click:WHOIS]
file=whois-rightclick.ini
```
Created the following files in /moloch/wiserService/
virustotal-rightclick.ini
```
[right-click]
VTIP=url:https://www.virustotal.com/en/ip-address/%TEXT%/information/;name:Virus Total IP;category:ip
VTHOST=url:https://www.virustotal.com/en/domain/%HOST%/information/;name:Virus Total Host;category:host
VTURL=url:https://www.virustotal.com/latest-scan/%URL%;name:Virus Total URL;category:url
```
anomaly-rightclick.ini
```
[right-click]
ANOMHOST=url:https://ui.threatstream.com/detail/domain/%HOST%;name:Anomaly ThreatStream;category:host
ANOMIP=url:https://ui.threatstream.com/detail/ip/%TEXT%;name:Anomaly ThreatStream;category:ip
```
alienvault-rightclick.ini
```
[right-click]
OTXIP=url:https://www.alienvault.com/open-threat-exchange/dashboard#/my/reputation-monitor/%TEXT%;name:AlienVault IP lookup;category:ip
```
whois-rightclick.ini
```
[right-click]
WHOISHOST=url:https://whois.icann.org/en/lookup?name=%HOST%;name:WHOIS host lookup;category:host
```
attempting to click on either src ip, dst ip, or host on the default sessions tab, none of the options show.
**Misc Output**:
Output of curl http://localhost:port/rightClicks:
```
{"VTIP":{"url":"https://www.virustotal.com/en/ip-address/%TEXT%/information/","name":"Virus Total IP","category":"ip"},"VTHOST":{"url":"https://www.virustotal.com/en/domain/%HOST%/information/","name":"Virus Total Host","category":"host"},"VTURL":{"url":"https://www.virustotal.com/latest-scan/%URL%","name":"Virus Total URL","category":"url"},"ANOMHOST":{"url":"https://ui.threatstream.com/detail/domain/%HOST%","name":"Anomaly ThreatStream","category":"host"},"ANOMIP":{"url":"https://ui.threatstream.com/detail/ip/%TEXT%","name":"Anomaly ThreatStream","category":"ip"},"OTXIP":{"url":"https://www.alienvault.com/open-threat-exchange/dashboard#/my/reputation-monitor/%TEXT%","name":"AlienVault IP lookup","category":"ip"},"WHOISHOST":{"url":"https://whois.icann.org/en/lookup?name=%HOST%","name":"WHOIS host lookup","category":"host"}}
```
Output of /molochRightClick in browser:
```
{"httpAuthorizationDecode":{"fields":"http.authorization","func":"{    if (value.substring(0,5) === \"Basic\")       return {name: \"Decoded:\", value: atob(value.substring(6))};    return undefined;  }"},"VTIP":{"url":"https://www.virustotal.com/en/ip-address/%TEXT%/information/","name":"Virus Total IP","category":"ip"},"VTHOST":{"url":"https://www.virustotal.com/en/domain/%HOST%/information/","name":"Virus Total Host","category":"host"},"VTURL":{"url":"https://www.virustotal.com/latest-scan/%URL%","name":"Virus Total URL","category":"url"},"ANOMHOST":{"url":"https://ui.threatstream.com/detail/domain/%HOST%","name":"Anomaly ThreatStream","category":"host"},"ANOMIP":{"url":"https://ui.threatstream.com/detail/ip/%TEXT%","name":"Anomaly ThreatStream","category":"ip"},"OTXIP":{"url":"https://www.alienvault.com/open-threat-exchange/dashboard#/my/reputation-monitor/%TEXT%","name":"AlienVault IP lookup","category":"ip"},"WHOISHOST":{"url":"https://whois.icann.org/en/lookup?name=%HOST%","name":"WHOIS host lookup","category":"host"}}
```
**Error Logs**:
console output from chrome v62:
```
vendor.bundle.js:33 RangeError: Invalid time value
at Date.toISOString (<anonymous>)
at l.value (app.bundle.js:37)
at app.bundle.js:37
at u (vendor.bundle.js:33)
at vendor.bundle.js:33
at h.$digest (vendor.bundle.js:33)
at h.$apply (vendor.bundle.js:33)
at u (vendor.bundle.js:32)
at m (vendor.bundle.js:32)
at XMLHttpRequest.w.onload (vendor.bundle.js:32) "Possibly unhandled rejection: {}"
```

Console output from Firefox 56.0.1 (64-bit):
```
RangeError: invalid date
Stack trace:
value@https://moloch:port/app.bundle.js:37:24552
value/<@https://moloch:port/app.bundle.js:37:21442
u@https://moloch:port/vendor.bundle.js:33:7536
l/<@https://moloch:port/vendor.bundle.js:33:7941
$digest@https://moloch:port/vendor.bundle.js:33:13650
$apply@https://moloch:port/vendor.bundle.js:33:15462
u@https://moloch:port/vendor.bundle.js:32:22438
m@https://moloch:port/vendor.bundle.js:32:24893
zt/</w.onload@https://moloch:port/vendor.bundle.js:32:25312
 Possibly unhandled rejection: {}
```

**Comment by awick** [comment] 2017-10-25 16:53
duplicate of #740

**Closed by awick** 2017-10-25 16:53 UTC
