### ISSUE TITLE
Suricata Plugin

### ISSUE THREAD

**Issue by a3ilson** [aol/moloch#1174] opened 2019-09-24 23:51 UTC
**Elasticsearch version**:7.3.1

**Moloch version**:2.0.0

**OS name and version**:Ubuntu 18.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) deb

**Provide logs, stack traces and steps to reproduce**:
(1) enabled and configured suricata 
(2) navigated to SPIView
(3) loaded all under suricata 
(4) click on one of the signatures (i.e. generate a filter to pivot)
(5) filter output = "suricata.signature == SURICATA STREAM excessive retransmissions"
(5a) results in an error
(5b) to remedy/fix you have to add quotations after the == (example: suricata.signature == "SURICATA STREAM excessive retransmissions")

Low Priority Issue

**Comment by awick** [comment] 2019-09-25 00:01
Duplicate of #1146 already fixed in 2.0.1, please upgrade

**Closed by awick** 2019-09-25 00:01 UTC
