### ISSUE TITLE
Configure script creates wrong logrotate file

### ISSUE THREAD

**Issue by johnklasa** [aol/moloch#631] opened 2017-02-15 13:24 UTC
**Elasticsearch version**:
5.1.2

**Moloch version**:
0.17.1 RPM package

**OS name and version**:
RedHat Enterprise 7.3

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...)
RPM

**Provide logs, stack traces and steps to reproduce**:
Run Configure script and it creates a moloch logrotate file with /nids instead of /data

see line 104 and line 105 in the Configure script

**Comment by awick** [comment] 2017-02-15 13:25
Duplicate of #626

**Closed by awick** 2017-02-15 13:25 UTC
